name: Generate Snake Animation
on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        id: snake-svg
        with:
          github_user_name: Mahrokh-M
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00FFAA&color_dots=#1a1a1a,#2a2a2a,#3a3a3a,#4a4a4a,#5a5a5a
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
